### ISSUE TITLE
progress value NaN crash 

### ISSUE THREAD

**Issue by Bayramito** [alantoa/react-native-awesome-slider#76] opened 2024-07-10 08:34 UTC
<img width="389" alt="Ekran Resmi 2024-07-10 11 32 50" src="https://github.com/alantoa/react-native-awesome-slider/assets/44513402/2f780a45-c63d-40fe-9330-1391bcc1af36">

**Comment by CalvinNFT** [comment] 2024-08-13 11:23
This issue most likely is caused by the type of progress input value. Note the value should not be a number directly:

```javascript
progress={20}

// instead use

const progressValue = useSharedValue(20);
progress={progressValue}
```

If your issue is not resolved by this, please produce information to replicate the issue.

**Comment by alantoa** [comment] 2024-10-21 16:20
yeah, it's best to add your example code so I can take a look.

**Closed as completed** 2024-12-18 06:08 UTC
